using System.Windows;
using Drawing = System.Drawing;
using WinForms = System.Windows.Forms;

namespace Winfred;

/// <summary>
/// Winfred's top-hat mark. The .ico is generated by tools\make-icon.ps1; the same
/// shape is drawn as vector XAML by the WinHatMark template in App.xaml.
/// </summary>
public static class Branding
{
    public static readonly Uri IconUri = new("pack://application:,,,/Assets/winfred.ico");

    /// <summary>
    /// The mark at tray size. Falls back to the generic application icon if the
    /// resource is somehow missing, since a launcher with no tray icon is unquittable.
    /// </summary>
    public static Drawing.Icon TrayIcon()
    {
        try
        {
            var resource = Application.GetResourceStream(IconUri);
            if (resource == null) return Drawing.SystemIcons.Application;
            using var stream = resource.Stream;
            return new Drawing.Icon(stream, WinForms.SystemInformation.SmallIconSize);
        }
        catch
        {
            return Drawing.SystemIcons.Application;
        }
    }
}
